### ISSUE TITLE
Repeated statement on the EVM Functions call page

### ISSUE THREAD

**Issue by michojekunle** [0xMacro/library#275]
I came across a tweet on X (formerly Twitter) about this post and decided to read it. and then noticed a repeated statement as shown in the image below. 

I'd like to edit that part and remove the duplicated statement 

This page is well detailed, and I enjoyed reading through it, and I would also love to contribute more to this library cause its a field that piques my interest

![Screenshot 2024-11-02 175711](https://github.com/user-attachments/assets/9cae097e-3113-4b0b-8957-8b4d9c043167)

**Comment by gilbert** [comment]
Glad to have you Michael, and thanks for your PR 🙂
