### ISSUE TITLE
Incorrect description of memory length

### ISSUE THREAD

**Issue by KumaCrypto** [0xMacro/library#94]
Hi, you are doing cool stuff!

I want to make a clarification, in the chapter about [memory](https://github.com/0xMacro/library/blob/49b743ac1d27fc79008eab4cdb54210daf852741/client/learn_evm/chapters/evm/memory.html#L42) you write: "Memory on the EVM is essentially a 2^256 length string", while the [`Go Ethereum` implementation](https://github.com/ethereum/go-ethereum/blob/7f756dc1185d7f1eeeacb1d12341606b7135f9ea/core/vm/instructions.go#L500-L505) uses `uint64` for memory size, so the maximum length of memory is 2^64 - 1 :)

**Comment by Bschuster3434** [comment]
@KumaCrypto, thank you for the comment! While I can't speak to the Geth implementation, according to the EVM Yellow paper, the memory on the EVM is 2^256 bits. Using [the following reference](https://ethereum.org/es/developers/tutorials/yellow-paper-evm/#:~:text=The%20EVM%20also%20has%20a,organized%20into%2032%2Dbyte%20words.):

> The EVM also has a volatile space called memory which is used to store data during execution. This memory is organized into 32-byte words.

32 bytes being 256 bits, allowing for a 2^256 value.

Feel free to let me know if you have any questions. I am closing for now unless I missed something.
